### ISSUE TITLE
Question about persisting the login information 

### ISSUE THREAD

**Issue by Ericvf** [microsoftgraph/msgraph-sample-blazor-clientside#71] opened 2023-04-15 18:49 UTC
This was a great sample, thanks a lot for it! The sample works as expected but I have on additional requirement, which is the ability to keep the user logged in as long as possible. 

I've used the line below to achieve that via localStorage. However, when the token expires an exception will be thrown. I'm trying to find out how to refresh the token or at least redirect the user to the login page again. Right now I have to delete the localStorage in order to get the app to run again. Manually browsing to /authentication/login does not work in this state. 

`options.ProviderOptions.Cache.CacheLocation = "localStorage";`

Does anyone have a good tip to solve that?

**Comment by jasonjoh** [comment] 2023-04-17 14:30
@Ericvf MSAL should be handling refreshing tokens for you. What's the behavior you are seeing? Does it stop working after an hour?

**Comment by Ericvf** [comment] 2023-04-17 16:45
Thanks for the response. I'm not sure about the timeframe, but it seems several hours. The result will be that the AuthorizeRouteView will give the javascript error: 

> Unhandled exception rendering component: Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown.
Microsoft.Graph.Models.ODataErrors.ODataError: Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown.
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes)
   at Microsoft.Kiota.Http.Http

If I inspect the Network tabs in DevTools I see that the HTTP request failed: 
> AADSTS70000: The user could not be authenticated as the grant is expired. The user must sign in again.

For some reason the JavaScript library is having an issue with handeling this scenario.  I'm not sure how to proceed with this yet, I've tried to change the LoginMode to redirect but it has the same issue. I'm experiencing this on all devices and browsers. 

The sourcecode of my app can be found here:
https://github.com/Ericvf/Timecop/tree/Workinprogress

**Comment by jasonjoh** [comment] 2023-04-18 13:23
Strange, I can't reproduce it in the sample. The only thing I can think of is if your organization has modified the lifetime of refresh tokens to be lower than default.

If you can reduce this to a simple repro it may be worth opening an issue with the auth library in this repo: https://github.com/dotnet/aspnetcore.

**Comment by Ericvf** [comment] 2023-04-23 11:06
Thanks, I'm going to try and reproduce it based on the sample and I will net you know

**Comment by jasonjoh** [comment] 2023-04-24 16:54
Thanks! I'm going to close this issue for now. If you find out there's a bug in the sample please let us know.

**Closed by jasonjoh** 2023-04-24 16:54 UTC
Labels: cannot repro
